apiVersion: v1
kind: Service

metadata:
  name: ipl-ticket-booking-service

spec:
  type: {{ .Values.service.type }}

  selector:
    app: ipl-ticket-booking

  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}